name: smart_finance_wallet
description: A Smart Finance Wallet app with Firebase, Hive, and Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Features
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.0.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.4.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  timezone: ^0.9.4
  uuid: ^4.5.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .env
